# Generated by Django 5.1.3 on 2024-12-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('reportado_por', models.CharField(max_length=100)),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('responsable', models.CharField(max_length=30)),
                ('fecha_solucion', models.DateTimeField(blank=True)),
                ('acciones_realizadas', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
