# Generated by Django 5.1.3 on 2024-12-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fecha_solucion',
            field=models.DateTimeField(null=True),
        ),
    ]
