# Generated by Django 5.1.3 on 2024-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_fecha_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fecha_solucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
