# Generated by Django 5.1.3 on 2024-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_fecha_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='prioridad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='responsable',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
