# Generated by Django 5.1.3 on 2024-12-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_estado_alter_incident_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='revisado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
